language: node_js
node_js:
  - '8'
branches:
  only:
    - master
install:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages
  - npm install
script:
  - npm run build:github
after_script:
  - ngh
cache:
  directories:
    - node_modules
env:
  global:
    - GH_REF: github.com/floguerin/stbui.git

